"use client";

import { useMemo } from "react";
import { Plus, RefreshCw, RotateCcw, Route, Scissors, Trash2, WandSparkles } from "lucide-react";
import { detectAdjacencies } from "@/engine/adjacency";
import { bounds } from "@/engine/geometry";
import { getPattern, PATTERNS } from "@/patterns/library";
import { generateDocumentWeave } from "@/engine/patternGenerator";
import { useStudioStore } from "@/store/useStudioStore";
import type { CrossingMode, CutMode, CutScope, TransitionStrategy } from "@/types/weave";

function NumberField({ label, value, min, max, step = 1, unit, onChange }: { label: string; value: number; min: number; max: number; step?: number; unit: string; onChange: (value: number) => void }) {
  return <label className="field-row"><span>{label}</span><span className="number-input"><input type="number" value={Number(value.toFixed(1))} min={min} max={max} step={step} onChange={(event) => onChange(Number(event.target.value))} /><em>{unit}</em></span></label>;
}
function RangeField({ label, value, min, max, unit, onChange }: { label: string; value: number; min: number; max: number; unit: string; onChange: (value: number) => void }) {
  return <label className="range-field"><span><b>{label}</b><output>{Math.round(value)}{unit}</output></span><input type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>;
}
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return <label className="field-row color-field"><span>{label}</span><span><input type="color" value={value} onChange={(event) => onChange(event.target.value)} /><code>{value.toUpperCase()}</code></span></label>;
}

const crossingLabels: Record<CrossingMode, string> = { alternate: "一上一下", "a-over": "方向 A 始终在上", "b-over": "方向 B 始终在上", "two-two": "两上两下", "three-one": "三上一下", custom: "自定义序列" };
const strategyLabels: Record<TransitionStrategy, string> = { "spacing-gradient": "间距渐变", "count-gradient": "条数渐变", "width-gradient": "宽度渐变", "direction-rotation": "方向旋转", "frequency-shift": "编织频率变化", "skip-weave": "逐渐抽空 / 跳编", "merge-split": "合并与分叉", "fan-out": "扇形发散", "pattern-morph": "纹样变形", "bridge-pattern": "桥接纹样" };

export function PropertyPanel() {
  const project = useStudioStore((state) => state.project); const selectedRegionId = useStudioStore((state) => state.selectedRegionId);
  const selectedTransitionId = useStudioStore((state) => state.selectedTransitionId); const selectedStripId = useStudioStore((state) => state.selectedStripId);
  const selectedCrossingId = useStudioStore((state) => state.selectedCrossingId); const selectedDirectionLayerId = useStudioStore((state) => state.selectedDirectionLayerId);
  const activeTool = useStudioStore((state) => state.activeTool); const cutLine = useStudioStore((state) => state.cutLine);
  const region = project.regions.find((item) => item.id === selectedRegionId); const transition = project.transitions.find((item) => item.id === selectedTransitionId);
  const pattern = region ? getPattern(region.pattern.patternId, project.customPatterns) : null; const box = region ? bounds(region.boundary) : null;
  const adjacencies = detectAdjacencies(project.regions); const actions = useStudioStore.getState();
  const weave = useMemo(() => generateDocumentWeave(project.regions, project.appearance, project.customPatterns), [project.regions, project.appearance, project.customPatterns]); const crossing = weave.crossings.find((item) => item.id === selectedCrossingId);
  const strip = weave.strips.find((item) => item.baseStripId === selectedStripId || item.id === selectedStripId);
  return <aside className="panel property-panel">
    <div className="panel-title-row"><div><span className="eyebrow">INSPECTOR · V4</span><h2>属性</h2></div><span className="selection-pill">{transition ? "过渡" : crossing ? "交点" : selectedStripId ? "竹条" : selectedDirectionLayerId ? "方向层" : region ? "区域" : "画板"}</span></div>
    <div className="inspector-scroll">
      {activeTool === "cut" ? <section className="property-section cut-panel"><div className="transition-heading"><div><h3>切割竹条</h3><p>{cutLine ? "已绘制切割线，请确认范围" : "在画板上拖出一条切割线"}</p></div><Scissors /></div>{cutLine ? <><label className="select-field"><span>适用范围</span><select value={cutLine.scope} onChange={(event) => actions.updateCutLine({ scope: event.target.value as CutScope, regionId: region?.id, directionLayerId: selectedDirectionLayerId ?? undefined })}><option value="all">全部竹条</option><option value="region">当前区域</option><option value="layer">当前方向层</option><option value="direction">同方向竹条</option><option value="selected">已选竹条</option></select></label><label className="select-field"><span>切割模式</span><select value={cutLine.mode} onChange={(event) => actions.updateCutLine({ mode: event.target.value as CutMode })}><option value="split">分割并保留两侧</option><option value="keep-left">只保留左侧</option><option value="keep-right">只保留右侧</option><option value="delete-left">删除左侧</option><option value="delete-right">删除右侧</option></select></label><div className="transition-actions"><button className="danger" onClick={() => actions.setCutLine(null)}>取消</button><button onClick={() => actions.applyCut()}><Scissors />应用切割</button></div></> : null}</section> : null}
      {!region && !transition ? <><section className="property-section"><h3>画板</h3><div className="two-columns"><NumberField label="宽" value={project.canvas.width} min={160} max={1000} unit="mm" onChange={(value) => actions.updateCanvas(value, project.canvas.height)} /><NumberField label="高" value={project.canvas.height} min={120} max={800} unit="mm" onChange={(value) => actions.updateCanvas(project.canvas.width, value)} /></div><label className="check-row"><span>显示网格</span><input type="checkbox" checked={project.canvas.gridVisible} onChange={(event) => actions.updateCanvasConfig({ gridVisible: event.target.checked })} /></label><label className="check-row"><span>吸附网格</span><input type="checkbox" checked={project.canvas.snapEnabled} onChange={(event) => actions.updateCanvasConfig({ snapEnabled: event.target.checked })} /></label><NumberField label="网格大小" value={project.canvas.gridSize} min={2} max={50} unit="mm" onChange={(value) => actions.updateCanvasConfig({ gridSize: value })} /></section><section className="property-section transition-summary"><h3>结构关系</h3><div className="metric-grid"><div><strong>{project.regions.length - 1}</strong><span>设计区域</span></div><div><strong>{adjacencies.length}</strong><span>检测邻接</span></div><div><strong>{project.transitions.length}</strong><span>结构过渡</span></div></div><button className="generate-button primary" disabled={!adjacencies.length} onClick={() => actions.generateAllTransitions(adjacencies)}><WandSparkles />生成全部结构过渡</button></section></> : null}
      {region && pattern && box ? <>
        <section className="property-section"><h3>区域 <small>{region.boundary.length} 个节点</small></h3><label className="text-field"><span>名称</span><input value={region.name} onChange={(event) => actions.updateRegion(region.id, { name: event.target.value })} /></label><label className="select-field"><span>纹样定义</span><select value={region.pattern.patternId} onChange={(event) => actions.applyPattern(region.id, event.target.value)}>{PATTERNS.map((item) => <option key={item.id} value={item.id}>{item.nameZh} / {item.nameEn}</option>)}</select></label><p className="pattern-description">Definition 决定拓扑；Dense / Open 等只作为 Variant 参数，不再冒充新纹样。</p></section>
        <section className="property-section"><h3>变换</h3><div className="two-columns"><NumberField label="X" value={box.x} min={-500} max={1000} unit="mm" onChange={(value) => actions.moveRegion(region.id, value - box.x, 0)} /><NumberField label="Y" value={box.y} min={-500} max={1000} unit="mm" onChange={(value) => actions.moveRegion(region.id, 0, value - box.y)} /><NumberField label="宽" value={box.width} min={10} max={1000} unit="mm" onChange={(value) => actions.resizeRegion(region.id, value / Math.max(1, box.width), 1)} /><NumberField label="高" value={box.height} min={10} max={800} unit="mm" onChange={(value) => actions.resizeRegion(region.id, 1, value / Math.max(1, box.height))} /></div><NumberField label="旋转" value={region.pattern.rotation} min={-180} max={180} unit="°" onChange={(value) => actions.rotateRegion(region.id, value - region.pattern.rotation)} /></section>
        <section className="property-section"><h3>Pattern Scale <small>只改变重复单元</small></h3><RangeField label="整体缩放" value={region.pattern.scale * 100} min={40} max={220} unit="%" onChange={(value) => actions.updatePatternInstance(region.id, { scale: value / 100, scaleX: value / 100, scaleY: value / 100 })} /><div className="two-columns"><NumberField label="Repeat W" value={pattern.structure.repeat.width * region.pattern.scaleX} min={5} max={200} unit="mm" onChange={(value) => actions.updatePatternInstance(region.id, { scaleX: value / pattern.structure.repeat.width, scale: value / pattern.structure.repeat.width })} /><NumberField label="Repeat H" value={pattern.structure.repeat.height * region.pattern.scaleY} min={5} max={200} unit="mm" onChange={(value) => actions.updatePatternInstance(region.id, { scaleY: value / pattern.structure.repeat.height })} /></div></section>
        <section className="property-section"><h3>Weave Density <small>改变数量与孔隙</small></h3><RangeField label="全局密度" value={region.pattern.density} min={20} max={140} unit="%" onChange={(value) => actions.updatePatternInstance(region.id, { density: value })} /></section>
        <section className="property-section"><div className="section-title-action"><h3>Direction Layers</h3><button title="新增方向层" onClick={() => actions.addDirectionLayer(region.id)}><Plus /></button></div>{region.pattern.directionLayers.map((layer, index) => <div className={`direction-card ${selectedDirectionLayerId === layer.id ? "selected" : ""}`} key={layer.id} onClick={() => actions.selectDirectionLayer(region.id, layer.id)}><div className="direction-card-title"><span><i style={{ transform: `rotate(${layer.angle}deg)` }} />方向 {index + 1} · {layer.angle}°</span><span><input type="checkbox" checked={layer.enabled} onClick={(event) => event.stopPropagation()} onChange={(event) => actions.updateDirectionLayer(region.id, layer.id, { enabled: event.target.checked })} /><button disabled={region.pattern.directionLayers.length <= 1} onClick={(event) => { event.stopPropagation(); actions.deleteDirectionLayer(region.id, layer.id); }}><Trash2 /></button></span></div><RangeField label="独立密度" value={layer.density} min={10} max={140} unit="%" onChange={(value) => actions.updateDirectionLayer(region.id, layer.id, { density: value })} /><div className="two-columns"><NumberField label="角度" value={layer.angle} min={-180} max={180} unit="°" onChange={(value) => actions.updateDirectionLayer(region.id, layer.id, { angle: value })} /><NumberField label="间距" value={layer.spacing} min={1} max={60} step={.5} unit="mm" onChange={(value) => actions.updateDirectionLayer(region.id, layer.id, { spacing: value })} /><NumberField label="条宽" value={layer.stripWidth} min={.8} max={16} step={.2} unit="mm" onChange={(value) => actions.updateDirectionLayer(region.id, layer.id, { stripWidth: value })} /><NumberField label="条数" value={layer.stripCount} min={0} max={120} unit="根" onChange={(value) => actions.updateDirectionLayer(region.id, layer.id, { stripCount: value })} /><NumberField label="水平偏移" value={layer.offsetX ?? 0} min={-500} max={500} step={1} unit="mm" onChange={(value) => actions.updateDirectionLayer(region.id, layer.id, { offsetX: value })} /><NumberField label="垂直偏移" value={layer.offsetY ?? 0} min={-500} max={500} step={1} unit="mm" onChange={(value) => actions.updateDirectionLayer(region.id, layer.id, { offsetY: value })} /><NumberField label="3D 高度" value={layer.zOffset ?? 0} min={-30} max={30} step={.5} unit="mm" onChange={(value) => actions.updateDirectionLayer(region.id, layer.id, { zOffset: value })} /></div><ColorField label="方向颜色" value={layer.color ?? region.color} onChange={(value) => actions.updateDirectionLayer(region.id, layer.id, { color: value })} /><label className="check-row"><span>锁定方向层</span><input type="checkbox" checked={layer.locked ?? false} onChange={(event) => actions.updateDirectionLayer(region.id, layer.id, { locked: event.target.checked })} /></label></div>)}</section>
        <section className="property-section"><h3>Crossing Rules</h3>{crossing ? <div className="crossing-selected"><b>已选交点</b><code>{crossing.id}</code><span>当前在上：{crossing.overStripId === crossing.stripA ? "竹条 A" : "竹条 B"}</span><button onClick={() => actions.toggleCrossing(region.id, crossing.id, crossing.stripA, crossing.stripB, crossing.overStripId)}><RotateCcw />交换 Over / Under</button></div> : null}{region.pattern.crossingRules.length ? region.pattern.crossingRules.map((rule) => { const a = region.pattern.directionLayers.find((item) => item.id === rule.directionAId); const b = region.pattern.directionLayers.find((item) => item.id === rule.directionBId); return <label className="select-field crossing-rule" key={rule.id}><span>{a?.angle ?? "?"}° × {b?.angle ?? "?"}°</span><select value={rule.mode} onChange={(event) => actions.updateCrossingRule(region.id, rule.id, event.target.value as CrossingMode)}>{Object.entries(crossingLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>; }) : <p className="transition-note">新增第二个方向后可建立交织规则。</p>}<p className="transition-note">交点命中层已置于最上方，点击后会立即交换并同步 3D。</p></section>
        <section className="property-section"><h3>外观与图层</h3><ColorField label="区域基色" value={region.color} onChange={(value) => actions.updateRegion(region.id, { color: value })} /><label className="check-row"><span>显示</span><input type="checkbox" checked={region.visible} onChange={(event) => actions.updateRegion(region.id, { visible: event.target.checked })} /></label><label className="check-row"><span>锁定</span><input type="checkbox" checked={region.locked} onChange={(event) => actions.updateRegion(region.id, { locked: event.target.checked })} /></label></section>
        {selectedStripId ? <section className="property-section strip-section"><div className="section-title-action"><h3>单根竹条 <small>{strip?.sourceType === "manual" ? "Manual" : "Generated"}</small></h3><button title="重置本根竹条" onClick={() => actions.resetStrip(region.id, selectedStripId)}><RotateCcw /></button></div><code className="strip-id">{selectedStripId}</code><ColorField label="颜色覆盖" value={region.pattern.localOverrides[selectedStripId]?.color ?? strip?.color ?? region.color} onChange={(value) => actions.updateStrip(region.id, selectedStripId, { color: value })} /><NumberField label="宽度覆盖" value={region.pattern.localOverrides[selectedStripId]?.width ?? strip?.width ?? region.pattern.stripWidth} min={1} max={14} step={.5} unit="mm" onChange={(value) => actions.updateStrip(region.id, selectedStripId, { width: value })} /><div className="two-columns"><NumberField label="X 偏移" value={region.pattern.localOverrides[selectedStripId]?.offsetX ?? 0} min={-500} max={500} unit="mm" onChange={(value) => actions.updateStrip(region.id, selectedStripId, { offsetX: value })} /><NumberField label="Y 偏移" value={region.pattern.localOverrides[selectedStripId]?.offsetY ?? 0} min={-500} max={500} unit="mm" onChange={(value) => actions.updateStrip(region.id, selectedStripId, { offsetY: value })} /><NumberField label="3D 高度" value={region.pattern.localOverrides[selectedStripId]?.zOffset ?? 0} min={-30} max={30} step={.5} unit="mm" onChange={(value) => actions.updateStrip(region.id, selectedStripId, { zOffset: value })} /></div><label className="check-row"><span>锁定竹条</span><input type="checkbox" checked={region.pattern.localOverrides[selectedStripId]?.locked ?? false} onChange={(event) => actions.updateStrip(region.id, selectedStripId, { locked: event.target.checked })} /></label></section> : null}
      </> : null}
      {transition ? <><section className="property-section"><div className="transition-heading"><div><h3>结构过渡</h3><p>{transition.regionIds.join(" ↔ ")}</p></div><Route /></div><label className="text-field"><span>名称</span><input value={transition.name} onChange={(event) => actions.updateTransition(transition.id, { name: event.target.value })} /></label><label className="select-field"><span>模式</span><select value={transition.mode} onChange={(event) => actions.updateTransition(transition.id, { mode: event.target.value as typeof transition.mode })}><option value="structural">Structural · 结构连续</option><option value="natural">Natural · 视觉自然</option><option value="decorative">Decorative · 装饰变化</option><option value="experimental">Experimental · 复杂分叉</option></select></label><label className="select-field"><span>策略</span><select value={transition.strategy} onChange={(event) => actions.updateTransition(transition.id, { strategy: event.target.value as TransitionStrategy })}>{Object.entries(strategyLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{transition.strategy === "bridge-pattern" ? <label className="select-field"><span>桥接纹样</span><select value={transition.bridgePatternIds[0] ?? "herringbone"} onChange={(event) => actions.updateTransition(transition.id, { bridgePatternIds: [event.target.value] })}>{PATTERNS.map((item) => <option key={item.id} value={item.id}>{item.nameZh}</option>)}</select></label> : null}</section><section className="property-section"><h3>连续变化</h3><RangeField label="过渡宽度" value={transition.width} min={16} max={140} unit="mm" onChange={(value) => actions.updateTransition(transition.id, { width: value })} /><RangeField label="平滑度" value={transition.smoothness} min={0} max={100} unit="%" onChange={(value) => actions.updateTransition(transition.id, { smoothness: value, stageCount: Math.round(4 + value / 7) })} /><RangeField label="复杂度" value={transition.complexity} min={0} max={100} unit="%" onChange={(value) => actions.updateTransition(transition.id, { complexity: value })} /><NumberField label="中间阶段" value={transition.stageCount} min={4} max={24} unit="层" onChange={(value) => actions.updateTransition(transition.id, { stageCount: value })} />{transition.strategy === "fan-out" ? <><RangeField label="发散强度" value={transition.fanStrength} min={0} max={100} unit="%" onChange={(value) => actions.updateTransition(transition.id, { fanStrength: value })} /><RangeField label="发散角度" value={transition.spreadAngle} min={0} max={120} unit="°" onChange={(value) => actions.updateTransition(transition.id, { spreadAngle: value })} /></> : null}<div className="transition-actions"><button onClick={() => actions.regenerateTransition(transition.id)}><RefreshCw />重新生成</button><button className="danger" onClick={() => actions.deleteTransition(transition.id)}><Trash2 />删除过渡</button></div><p className="transition-note">删除只移除 Transition，两个 Region 会完整保留。</p></section></> : null}
      <section className="property-section"><h3>3D 材料</h3><NumberField label="竹条厚度" value={project.appearance.thickness} min={.4} max={4} step={.2} unit="mm" onChange={(value) => actions.updateAppearance({ thickness: value })} /></section>
    </div>
  </aside>;
}
